name: dev

env:
  DOCKER_TAG: 1.1.${{ github.run_number }}
  APP_NAME: ${{ github.event.repository.name }}
  DOCKERHUB_USERNAME: erictik
 
on:
  workflow_dispatch:
  push:
    branches:
      - 'develop'
    paths:
      - '**.ts'

jobs:
  buildAndPush:
    env:
      TAG: ${{ github.env.DOCKERHUB_USERNAME }}/${{ github.env.APP_NAME }}:${{ github.env.DOCKER_TAG }}
      REPO: ${{ github.env.DOCKERHUB_USERNAME }}/${{ github.env.APP_NAME }}
      LATEST_TAG: ${{ github.env.DOCKERHUB_USERNAME }}/${{ github.env.APP_NAME }}:latest
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Set up QEMU
      uses: docker/setup-qemu-action@v2
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2
    - name: Login to DockerHub
      uses: docker/login-action@v2
      with:
        username: ${{ github.env.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}
    - name: Build Docker image
      uses: docker/build-push-action@v2
      with:
        context: .
        file: ./Dockerfile
        push: true
        platforms: linux/amd64
        # platforms: linux/amd64,linux/arm64
        tags: ${{ env.TAG }},${{ env.LATEST_TAG }}
